version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "monthly"
    groups:
      gomod:
        patterns:
          - "*"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # Workaround for https://github.com/dependabot/dependabot-core/issues/6345
      - "/.github/actions/*"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci(deps)"
