name: 'Run Tests'
description: 'Run project tests and generate coverage report'

inputs:
  build-path:
    description: >
      Path to the project's build directory
    default: 'build'
  source-path:
    description: >
      Path to the project's source directory
    default: '.'
  valgrind:
    description: 'Whether to run the tests with valgrind'
    default: 'false'
  coverage:
    description: 'Whether to generate a coverage report'
    default: 'false'
  gcov:
    description: 'Gcov executable to use'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run tests
      id: run-tests
      working-directory: ${{ inputs.source-path }}
      run: go test ./... -v
      shell: bash
